### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by csthenry** [DavidNery/flarum-nickname-group-formatter#1]
Hi,developer,
We hope that this nickname color will not be effective in the user tag card, because the nickname color may conflict with the card background. Thank you.

**Comment by DavidNery** [comment]
Hi Henry, thanks for your suggestion.

Since I'm not focusing on the flarum, I didn't give attention to the extension.
I did what you wanted, but I need to think about the other forum administrators, whether they like it or not. Therefore, I am adding a config to the extension that administrators can enable or disable color on user cards.

Are you still using the extension? If yes, I will do it as soon as possible

Edit: and update to flarum 14

**Comment by csthenry** [comment]
thank you for you support,but...my flarum core is beta13.because beta14 can not supprot some extension in need.

**Comment by DavidNery** [comment]
Done. Thanks for your suggestion.
